language: rust
cache: cargo
os:
- linux
- osx
- windows
rust:
- stable
install:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update && sudo apt-get install
  -y libfuse-dev; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update && brew tap homebrew/homebrew-cask
  && brew cask install osxfuse; fi
script:
- cargo build -v --release
- cargo test -v --release
env:
  global:
  - RUST_BACKTRACE=1
before_deploy:
  - mkdir deploy
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then export EXECUTABLE_NAME=save3ds_fuse.exe else then export EXECUTABLE_NAME=save3ds_fuse
  - zip deploy/save3ds-$TRAVIS_TAG-$TRAVIS_COMMIT-$TRAVIS_OS_NAME.zip target/release/$EXECUTABLE_NAME
deploy:
  provider: releases
  api_key:
    secure: NtDeADmiguc/T8pRn+7WVTIgqBP8s5goNIAe20oCEdvOKEMNbJbQmlmWEK9mYeWAH2HAw36oBUf0JZAKKdb/7Xc+yuZc3D71JeRRvnCv5rvAUnxRd/ry32ayyoaYp3gb2rMLn2+rr7YF2xOCiG+eCLbMDK8LH/xLkoxveDWgtk3GepOi4wg5yGw0Hzkmy6loqueicWmn0eGXXXzAGulyS7SmYIfJA3uyS+ObhRbRVbmYDPKu5qRympDKUwlhQnonATm5itylboxsaRt127zDkasE9ienC+YS802go1LZx7ppnq5Wr8vHIPWtC4h/G/Agn5fqnLXR4HFY4AA9K/vBpBRhtNP1BySsXTjlyl8JYE1xJKKl/zo+WAOaq0x+Hvs5y8Ofa2nlw+X8PVP6GW1K+yIJpq7OsQa2nUIZgh1SqO4JN6MAFtHizl4P8SzwDJfmDd+xOj2Do/2ZvJz3BUf4aVldnjmQ9N2xqG81NyfqelgezjYMnffS3bovxabrlsZ1O9wRhd5Y9DWl24aTv9EC6uUZvjji+Gs59S5eJzMHg8Ip5CP4qeSFbforK+6pMosV7KOcwSgUamxQnxRmnVEj5NLAFlDVUu/FmQ55r7CN11q/ALvTQGTAu8DvrbPQPdmy9Qj+mbYDERFrOFUVp3GFMmJXAqs4L6sP96wCVjjIQZw=
  file_glob: true
  file: deploy/*
  skip_cleanup: true
  on:
    tags: true
    repo: wwylele/save3ds
