
language: rust
cache: cargo
os:
  - linux
  - osx
  - windows
rust:
  - stable
install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update && sudo apt-get install -y libfuse-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update && brew tap homebrew/homebrew-cask && brew cask install osxfuse; fi
script:
  - cargo build -v
  - cargo test -v

env:
  global:
    - RUST_BACKTRACE=1
