[package]
name = "libsave3ds_c"
version = "0.1.0"
authors = ["Weiyi Wang <wwylele@gmail.com>"]
edition = "2018"

[dependencies]
libsave3ds = { path = "../libsave3ds" }

[lib]
name = "save3ds_c"
crate-type = ["staticlib"]
